export const cars = [
  {
    id: 1,
    name: "Maruti WagonR",
    category: "Hatchback",
    price: 1500,
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=800",
    transmission: "Manual",
    fuel: "Petrol/CNG",
    seats: 5,
  },
  {
    id: 2,
    name: "Maruti Swift",
    category: "Hatchback",
    price: 1800,
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
  },
  {
    id: 3,
    name: "Maruti Baleno",
    category: "Premium Hatchback",
    price: 2000,
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=800",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
  },
  {
    id: 4,
    name: "Hyundai i20",
    category: "Premium Hatchback",
    price: 2200,
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
  },
  {
    id: 5,
    name: "Mahindra Thar",
    category: "SUV",
    price: 4500,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800",
    transmission: "Manual",
    fuel: "Diesel",
    seats: 4,
  },
  {
    id: 6,
    name: "Maruti Ertiga",
    category: "MUV",
    price: 3500,
    image: "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80&w=800",
    transmission: "Manual",
    fuel: "CNG/Petrol",
    seats: 7,
  },
  {
    id: 7,
    name: "Hyundai Creta",
    category: "SUV",
    price: 3800,
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&q=80&w=800",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 5,
  },
  {
    id: 8,
    name: "Toyota Innova Crysta",
    category: "Premium MUV",
    price: 5000,
    image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&q=80&w=800",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 7,
  },
  {
    id: 9,
    name: "Mahindra XUV700",
    category: "Luxury SUV",
    price: 5500,
    image: "https://images.unsplash.com/photo-1503376712341-ea192a550186?auto=format&fit=crop&q=80&w=800",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 7,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rahul Sharma",
    rating: 5,
    text: "Excellent service! The car was clean and well-maintained. The booking process was seamless via WhatsApp.",
    location: "Navi Mumbai"
  },
  {
    id: 2,
    name: "Priya Patil",
    rating: 5,
    text: "Rented a Thar for a weekend trip to Lonavala. Best rates in Panvel and very professional support.",
    location: "Panvel"
  },
  {
    id: 3,
    name: "Amit Verma",
    rating: 4,
    text: "Smooth experience. The car was delivered on time and the condition was as promised. Highly recommended.",
    location: "Kharghar"
  }
];
